FROM continuumio/miniconda3:latest
LABEL author="carisdak@hawaii.edu"

RUN apt-get update && apt-get install -y procps git && apt-get clean -y

COPY conda_env.yml /
RUN conda env create -f /conda_env.yml && conda clean -a
COPY diamond /opt/conda/envs/nf-station-aloha/bin

RUN git clone https://bitbucket.org/MAVERICLab/stampede-clustergenomes.git \
    && mv stampede-clustergenomes /opt

ENV PATH /opt/conda/envs/nf-station-aloha/bin:/opt/stampede-clustergenomes/bin$PATH
