FROM continuumio/miniconda3:latest
LABEL author="carisdak@hawaii.edu"

RUN apt-get update && apt-get install -y procps git && apt-get clean -y

COPY conda_env.yml /
RUN conda env create -f /conda_env.yml && conda clean -a

#=================================================#
#============== CAMISIM from GitHub ==============#
#=================================================#

RUN git clone https://github.com/CAMI-challenge/CAMISIM.git \
    && mv CAMISIM /opt

WORKDIR /workspace

ENV PATH /opt/conda/envs/camisim/bin:/opt/CAMISIM:$PATH
