container:
	sudo docker build -f dockerfile -t nakor/coconet-paper-camisim . \
	&& sudo docker push nakor/coconet-paper-camisim \
	&& rm -f ~/.singularity_images.cache/nakor-coconet-paper-camisim.img
